name: Go checks

on:
  pull_request:
    branches:
      - main

jobs:
  backend-integration-test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: relational

      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://user:password@localhost:5432/relational?sslmode=disable
      GOOSE_MIGRATION_DIR: migrations

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version: "1.25"
          cache: True
          cache-dependency-path: backend/go.sum

      - uses: docker/setup-compose-action@v1
        with:
          version: latest

      - name: Install goose
        working-directory: backend
        run: go build -o $(go env GOPATH)/bin/goose github.com/pressly/goose/v3/cmd/goose

      - name: spinup-db
        run: |
          make db-up
